//ACTION TYPE CONST
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE'

//INICIA SOLICITUD
export const LOADING = 'START'
//TERMINA SOLICITUD FALLIDA
export const FAIL = 'FAIL'
//ACCOUNT CONST
export const REGISTER_SUCCESS= 'REGISTER_SUCCESS'
//SESION CONST
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'
